# Generated by Django 4.1.3 on 2022-12-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0005_alter_lugar_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='inicio',
            field=models.CharField(max_length=50),
        ),
    ]
