# Generated by Django 4.1.3 on 2022-12-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0007_alter_lugar_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
