# Generated by Django 4.1.3 on 2022-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0008_lugar_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='activo',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
