# Generated by Django 4.1.3 on 2022-12-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0009_lugar_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='termino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
