# Generated by Django 4.1.3 on 2022-12-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0010_alter_lugar_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
