# Generated by Django 4.1.3 on 2022-12-21 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sReservas', '0012_alter_lugar_inicio_alter_lugar_termino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
