# Generated by Django 4.1 on 2022-12-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_remove_reserva_fecha_remove_reserva_horatermino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
